### ISSUE TITLE
snwe went hidden when opening atom

### ISSUE THREAD

**Issue by zoenglinghou** [blahsd/snwe#44]
Sometimes when I open `atom` editor, `snwe` (running from `launchd`) disappears from all spaces. The `stderr` produces no additional output than the following, which is to be expected when `snwe` functions "normally":

```
2018-09-07 21:09:24.131 Electron[77177:2324018] *** WARNING: Textured window <AtomNSWindow: 0x7f9866f032d0> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
56:62: execution error: Can’t make «class pArt» of «class pTrk» of application "iTunes" into type string. (-1700)
```

**Comment by blahsd** [comment]
I can't replicate. How did you setup your launchd? Could it be that when launching atom the system finds an electron process already running and restarts it because it thinks it is the same thing? 

If you can narrow down more specific circumstances I can try something.

**Comment by zoenglinghou** [comment]
Here is my `snow.plist`:

```plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Disabled</key>
	<false/>
	<key>EnvironmentVariables</key>
	<dict>
		<key>PATH</key>
		<string>/Users/CarlosZhang/.nvm/versions/node/v10.9.0/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin</string>
	</dict>
	<key>Label</key>
	<string>com.carlos.snwe</string>
	<key>ProcessType</key>
	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Users/CarlosZhang/.nvm/versions/node/v10.10.0/bin/npm</string>
		<string>start</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/tmp/snwe.err</string>
	<key>StandardOutPath</key>
	<string>/tmp/snwe.out</string>
	<key>WorkingDirectory</key>
	<string>/Users/CarlosZhang/github/snwe</string>
</dict>
</plist>
```

Here is my `config.json`:

```json
{
	"version": "v0.1.0-rc.2.0.25",
	"hideIcon": "hideIcon",
	"theme": "/Users/CarlosZhang/github/snwe/app/css/flat_modified.css",
	"colorscheme": "/Users/CarlosZhang/github/snwe/app/css/colors-wal.css",
	"player": "/Users/CarlosZhang/github/snwe/app/js/require/iTunes.js",
	"commands": {
		"ssh": "ssh",
		"top": "top"
	},
	"modules": [
		{
			"filename": "desktop",
			"enabled": true
		},
		{
			"filename": "date",
			"enabled": true
		},
		{
			"filename": "player",
			"enabled": true
		},
		{
			"filename": "launcher",
			"enabled": false
		},
		{
			"filename": "taskbar",
			"enabled": false
		},
		{
			"filename": "chunkwm",
			"enabled": true
		},
		{
			"filename": "battery",
			"enabled": true
		},
		{
			"filename": "volume",
			"enabled": true
		},
		{
			"filename": "wifi",
			"enabled": true
		},
		{
			"filename": "settings",
			"enabled": true
		},
		{
			"filename": "time",
			"enabled": true
		}
	]
}
```

and my `flat_modified.css`

```css
:root {
  --top-margin    : 0px;
  --left-margin      : 0px;
  --right-margin     : 0px;
  --line-size        : 21px;
  --overflow-correct : 4px;
}

body {
  font-family    : "Hack Nerd Font";
  font-size      : 10 px;
  font-smoothing : antialiasing;
}

.bar {
  box-shadow: 0px 1px 5px 0px rgba(0,0,0,0.6);
  opacity: 1;
}

.widg {
  font-family:"Hack Nerd Font";
  font-size:11px;
  background-color: rgba(0,0,0,0);
  opacity: 0.8;
}

.button {
  padding-left: 4px;
  padding-right: 4px;
}
```

I use this [Workflow](https://github.com/franzheidl/alfred-workflows/tree/master/open-with-atom) to open atom.
